version: '3'
services:
    db:
        container_name: 'db'
        image: postgres:latest
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    backend:
        container_name: 'backend'
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: python:3.9-alpine
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

    redis:
        container_name: 'redis'
        image: redis:latest
        ports:
            - "6379:6379"
        env_file:
            - .env
        depends_on:
            - db

    rabbitmq:
        container_name: 'rabbitmq'
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        env_file:
            - .env
        depends_on:
            - db
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    celery:
        container_name: 'celery'
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: python:3.9-alpine
        env_file:
            - .env
        depends_on:
            - redis
        command: celery -A app worker -l info -Q default -n default@%h

    pgadmin:
        container_name: 'pgadmin'
        image: dpage/pgadmin4
        ports:
            - '80:80'
        env_file:
            - .env
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
